import 'app_colors.dart';
import '../../widgets/orb_background.dart';

/// Per-screen background orb placements, lifted from each frame in the design.
///
/// Generated from `design_ref/screens/*.html` — the offsets are in the source's
/// 393x852 coordinate space.
abstract final class ScreenOrbs {
  static const Map<String, List<Orb>> byId = {
    '01': [
      Orb(
        left: -150.0,
        top: -180.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 210.0,
        top: 90.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -90.0,
        top: 470.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 180.0,
        top: 660.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '02': [
      Orb(
        left: -110.0,
        top: -210.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 170.0,
        top: 130.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -130.0,
        top: 440.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 210.0,
        top: 690.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '03': [
      Orb(
        left: -180.0,
        top: -150.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 240.0,
        top: 60.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -60.0,
        top: 500.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 150.0,
        top: 630.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '04': [
      Orb(
        left: -150.0,
        top: -200.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 200.0,
        top: 110.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -100.0,
        top: 480.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 190.0,
        top: 670.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '05': [
      Orb(
        left: -160.0,
        top: -170.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 220.0,
        top: 80.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -80.0,
        top: 460.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 170.0,
        top: 650.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '06': [
      Orb(
        left: -130.0,
        top: -190.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 230.0,
        top: 120.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -110.0,
        top: 500.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 160.0,
        top: 680.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '07': [
      Orb(
        left: -170.0,
        top: -160.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 190.0,
        top: 70.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -70.0,
        top: 520.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 200.0,
        top: 640.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '08': [
      Orb(
        left: -140.0,
        top: -175.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 215.0,
        top: 100.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -95.0,
        top: 455.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 175.0,
        top: 665.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '09': [
      Orb(
        left: -165.0,
        top: -185.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 205.0,
        top: 135.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -85.0,
        top: 490.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 195.0,
        top: 655.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '10': [
      Orb(
        left: -120.0,
        top: -165.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 235.0,
        top: 95.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -120.0,
        top: 465.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 165.0,
        top: 690.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '11': [
      Orb(
        left: -155.0,
        top: -195.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 225.0,
        top: 115.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -75.0,
        top: 505.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 185.0,
        top: 645.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '12': [
      Orb(
        left: -155.0,
        top: -195.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 225.0,
        top: 115.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -75.0,
        top: 505.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 185.0,
        top: 645.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '13': [
      Orb(
        left: -145.0,
        top: -155.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 200.0,
        top: 85.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -105.0,
        top: 475.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 205.0,
        top: 675.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '14': [
      Orb(
        left: -125.0,
        top: -170.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 240.0,
        top: 105.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -115.0,
        top: 485.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 170.0,
        top: 660.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '15': [
      Orb(
        left: -170.0,
        top: -150.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 195.0,
        top: 140.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -70.0,
        top: 510.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 200.0,
        top: 635.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '16': [
      Orb(
        left: -150.0,
        top: -180.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 210.0,
        top: 125.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -100.0,
        top: 470.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 180.0,
        top: 670.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '17': [
      Orb(
        left: -165.0,
        top: -165.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 230.0,
        top: 90.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -85.0,
        top: 495.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 195.0,
        top: 650.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '18': [
      Orb(
        left: -135.0,
        top: -160.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 225.0,
        top: 80.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -95.0,
        top: 500.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 175.0,
        top: 655.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '19': [
      Orb(
        left: -155.0,
        top: -175.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 200.0,
        top: 115.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -75.0,
        top: 480.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 190.0,
        top: 665.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '20': [
      Orb(
        left: -140.0,
        top: -190.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 235.0,
        top: 100.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -110.0,
        top: 490.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 165.0,
        top: 675.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '21': [
      Orb(
        left: -175.0,
        top: -155.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 190.0,
        top: 130.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -65.0,
        top: 515.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 205.0,
        top: 640.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '22': [
      Orb(
        left: -130.0,
        top: -170.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 215.0,
        top: 120.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -90.0,
        top: 465.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 185.0,
        top: 680.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '23': [
      Orb(
        left: -160.0,
        top: -185.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 205.0,
        top: 95.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -80.0,
        top: 505.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 195.0,
        top: 660.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '24': [
      Orb(
        left: -145.0,
        top: -165.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 220.0,
        top: 110.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -100.0,
        top: 485.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 180.0,
        top: 650.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '25': [
      Orb(
        left: -170.0,
        top: -180.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 195.0,
        top: 125.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -70.0,
        top: 470.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 200.0,
        top: 685.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '26': [
      Orb(
        left: -150.0,
        top: -160.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 210.0,
        top: 105.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -95.0,
        top: 495.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 175.0,
        top: 665.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '27': [
      Orb(
        left: -165.0,
        top: -190.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 230.0,
        top: 85.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -75.0,
        top: 510.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 190.0,
        top: 645.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '28': [
      Orb(
        left: -135.0,
        top: -175.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 220.0,
        top: 120.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -105.0,
        top: 480.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 180.0,
        top: 660.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '29': [
      Orb(
        left: -170.0,
        top: -165.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 200.0,
        top: 95.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -80.0,
        top: 505.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 195.0,
        top: 670.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '30': [
      Orb(
        left: -140.0,
        top: -180.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 225.0,
        top: 110.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -90.0,
        top: 490.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 185.0,
        top: 655.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '31': [
      Orb(
        left: -160.0,
        top: -155.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 195.0,
        top: 130.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -70.0,
        top: 470.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 205.0,
        top: 685.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '32': [
      Orb(
        left: -145.0,
        top: -155.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 210.0,
        top: 140.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -85.0,
        top: 475.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 190.0,
        top: 660.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '33': [
      Orb(
        left: -165.0,
        top: -190.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 190.0,
        top: 90.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -75.0,
        top: 500.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 200.0,
        top: 650.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '34': [
      Orb(
        left: -155.0,
        top: -165.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 205.0,
        top: 115.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -95.0,
        top: 485.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 180.0,
        top: 665.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
    '35': [
      Orb(
        left: -170.0,
        top: -185.0,
        size: 440.0,
        color: AppColors.blue,
        opacity: .30,
      ),
      Orb(
        left: 195.0,
        top: 80.0,
        size: 340.0,
        color: AppColors.teal,
        opacity: .26,
      ),
      Orb(
        left: -70.0,
        top: 510.0,
        size: 420.0,
        color: AppColors.blueRoyal,
        opacity: .20,
      ),
      Orb(
        left: 205.0,
        top: 645.0,
        size: 260.0,
        color: AppColors.teal,
        opacity: .15,
      ),
    ],
  };

  /// Falls back to the home wash for any id without its own entry.
  static List<Orb> of(String id) => byId[id] ?? Orb.homeDefaults;
}
